[phases.setup]
nixpkgs = ["nodejs_18", "python310"]

[phases.install]
cmds = [
  "cd backend && pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[phases.start]
cmd = "uvicorn backend.app.main:app --host 0.0.0.0 --port 8000"
